# Generated by Django 4.2.3 on 2023-07-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('mac', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uned.user')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('code', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('angle_servo1', models.IntegerField(blank=True, null=True)),
                ('angle_servo2', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('light', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uned.device')),
            ],
        ),
    ]
