# Generated by Django 4.0.4 on 2023-07-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uned', '0002_alter_device_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
