# Generated by Django 4.2.3 on 2023-09-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uned', '0003_device_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataThermal',
            fields=[
                ('code', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('pixels', models.CharField(blank=True, max_length=1024, null=True)),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uned.device')),
            ],
        ),
    ]
